const seed=[{id:1,name:'Sarah Jones',role:'Plumber',type:'Hourly',rate:14,hours:202,normal:2184.20,current:2846.71,taxCode:'1257L',pension:'5%',student:'No'},{id:2,name:'Lewis Taylor',role:'Plumber',type:'Hourly',rate:14,hours:186.7,normal:2614,current:2614,taxCode:'1257L',pension:'5%',student:'No'},{id:3,name:'Emma Clarke',role:'Office Manager',type:'Salary',rate:28000,hours:0,normal:2333,current:2333,taxCode:'1257L',pension:'5%',student:'Plan 2'},{id:4,name:'Jake Wilson',role:'Apprentice',type:'Hourly',rate:9.5,hours:150.3,normal:1428,current:1428,taxCode:'1257L',pension:'3%',student:'No'},{id:5,name:'Chloe Brown',role:'Admin',type:'Salary',rate:24000,hours:0,normal:2000,current:2000,taxCode:'1257L',pension:'5%',student:'No'}];
let employees=JSON.parse(localStorage.getItem('spEmployees')||'null')||seed;let approved=localStorage.getItem('spApproved')==='1';let company=localStorage.getItem('spCompany')||"Dave's Plumbing Ltd";
const save=()=>localStorage.setItem('spEmployees',JSON.stringify(employees));const money=n=>'£'+Number(n||0).toLocaleString('en-GB',{minimumFractionDigits:2,maximumFractionDigits:2});const app=document.querySelector('#app');document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>render(b.dataset.view));
function render(v='home'){({home,people,pay,time,settings}[v]||home)()}
function demo(){return `<div class="demo">DEMO MODE · No real HMRC submissions or payments</div>`}
function home(){app.innerHTML=demo()+`<div class='top'><div><h1>Good afternoon 👋</h1><div class='muted'>${company}</div></div><b>SP</b></div><div class='grid' style='margin-top:20px'><section class='card'><div class='muted'>NEXT PAYDAY</div><h2>Friday 30 October</h2><div class='${approved?'ok':'muted'}'>${approved?'✓ October payroll approved':'October payroll is ready to review'}</div><div class='stats'><div class='stat'><b>${employees.length}</b>employees</div><div class='stat'><b>£34,821</b>net wages</div><div class='stat'><b>£9,418</b>tax & NI</div><div class='stat'><b>£2,104</b>pension</div></div>${approved?'':`<div class='warning'><b>⚠ 1 item needs checking</b><br>Sarah's pay is 30% higher than normal.</div><button class='btn' onclick='pay()'>Review payroll</button>`}</section><section class='card'><h3>Payroll checklist</h3><div class='check'>✓ Employee data loaded</div><div class='check'>✓ Hours received</div><div class='check'>✓ Demo calculations prepared</div><div class='check'>${approved?'✓':'○'} Employer approval</div><div class='check'>○ HMRC sandbox connection</div><div class='check'>○ Bank connection</div></section></div>`}
function people(){app.innerHTML=demo()+`<div class='top'><div><h1>People</h1><div class='muted'>${employees.length} employees</div></div><button class='btn' onclick='addEmployee()'>+ Add</button></div><div class='list' style='margin-top:18px'>${employees.map(e=>`<div class='row' onclick='profile(${e.id})'><div class='person'><span class='avatar'>${e.name[0]}</span><div><b>${e.name}</b><div class='muted'>${e.role} · ${e.type}</div></div></div><div><b>${e.type==='Salary'?money(e.rate)+'/yr':money(e.rate)+'/hr'}</b><div class='muted'>Next ${money(e.current)}</div></div></div>`).join('')}</div>`}
function profile(id){let e=employees.find(x=>x.id===id);app.innerHTML=demo()+`<button class='btn light' onclick='people()'>← People</button><div class='card' style='margin-top:14px'><div class='top'><div class='person'><span class='avatar'>${e.name[0]}</span><div><h2 style='margin:0'>${e.name}</h2><div class='muted'>${e.role}</div></div></div><button class='btn light' onclick='editEmployee(${id})'>Edit</button></div><div class='stats'><div class='stat'><b>${e.type==='Salary'?money(e.rate)+'/yr':money(e.rate)+'/hr'}</b>Pay</div><div class='stat'><b>${e.taxCode}</b>Tax code</div><div class='stat'><b>${e.pension}</b>Pension</div><div class='stat'><b>${money(e.current)}</b>Next pay</div></div><h3>What changed?</h3><p>${e.current!==e.normal?`Estimated pay is ${money(e.current-e.normal)} above this employee's normal amount.`:'Nothing unusual detected for this demo pay run.'}</p><button class='btn light' onclick='payslip(${id})'>Preview payslip</button></div>`}
function addEmployee(){employeeForm()}
function editEmployee(id){employeeForm(employees.find(x=>x.id===id))}
function employeeForm(e={}){app.innerHTML=demo()+`<h1>${e.id?'Edit':'Add'} employee</h1><div class='card form'><label>Full name</label><input id='n' value="${e.name||''}"><label>Job title</label><input id='r' value="${e.role||''}"><label>Pay type</label><select id='t'><option ${e.type==='Hourly'?'selected':''}>Hourly</option><option ${e.type==='Salary'?'selected':''}>Salary</option></select><label>Rate</label><input id='rate' type='number' step='.01' value="${e.rate||''}"><label>Tax code</label><input id='tax' value="${e.taxCode||'1257L'}"><button class='btn' onclick='saveEmployee(${e.id||0})'>Save employee</button></div>`}
function saveEmployee(id){let old=employees.find(x=>x.id===id),t=document.querySelector('#t').value,rate=+document.querySelector('#rate').value||0,obj={id:id||Date.now(),name:document.querySelector('#n').value||'New employee',role:document.querySelector('#r').value||'Employee',type:t,rate,hours:old?.hours||0,normal:old?.normal||0,current:old?.current||0,taxCode:document.querySelector('#tax').value||'1257L',pension:old?.pension||'Not set',student:old?.student||'No'};if(old)employees=employees.map(x=>x.id===id?obj:x);else employees.push(obj);save();people()}
function pay(){app.innerHTML=demo()+`<div class='top'><div><h1>October payroll</h1><div class='muted'>Payday · 30 October 2026</div></div><b class='pill'>${approved?'Approved':'Draft'}</b></div><div class='stats'><div class='stat'><b>${employees.length}</b>employees</div><div class='stat'><b>£34,821</b>net pay</div><div class='stat'><b>£9,418</b>tax & NI</div><div class='stat'><b>£48,967</b>company cost</div></div>${approved?'':`<div class='warning'><b>⚠ Sarah needs checking</b><br>Pay is higher than normal because of overtime. <button class='btn light' onclick='breakdown()'>Review</button></div>`}<section class='card scroll'><table class='paytable'><tr><th>Employee</th><th>Normal</th><th>This month</th><th>Status</th></tr>${employees.map(e=>`<tr onclick='payslip(${e.id})'><td>${e.name}</td><td>${money(e.normal)}</td><td><b>${money(e.current)}</b></td><td>${e.current===e.normal?'✓ Normal':'⚠ Check'}</td></tr>`).join('')}</table>${approved?`<p class='ok'><b>✓ Payroll locked in demo mode</b></p><button class='btn light' onclick='resetPayroll()'>Reset demo payroll</button>`:`<button class='btn green' style='margin-top:18px' onclick='confirmApprove()'>Approve October payroll</button>`}</section>`}
function breakdown(){app.innerHTML=demo()+`<button class='btn light' onclick='pay()'>← Payroll</button><div class='card detail'><h2>Sarah Jones</h2><div class='warning'><b>Why flagged?</b><br>Her demo pay is 30% above normal because 32 overtime hours were entered.</div><table class='paytable'><tr><td>Normal pay</td><td>£2,184.20</td></tr><tr><td>Overtime</td><td>+£662.51</td></tr><tr><th>Gross</th><th>£2,846.71</th></tr></table><button class='btn green' onclick='pay()'>Yes, that's expected</button></div>`}
function confirmApprove(){app.innerHTML=demo()+`<div class='card detail'><h1>Approve payroll?</h1><p>You are approving this <b>demo</b> payroll for ${employees.length} employees.</p><div class='warning'>This prototype will not contact HMRC or a bank.</div><button class='btn green' onclick='approve()'>Yes, approve demo payroll</button> <button class='btn light' onclick='pay()'>Cancel</button></div>`}
function approve(){approved=true;localStorage.setItem('spApproved','1');app.innerHTML=demo()+`<div class='success card'><div class='tick'>✓</div><h1>October payroll approved</h1><p>The demo pay run has been locked on this device.</p><div class='list mini'><div>✓ Payroll approved</div><div>✓ Demo payslips available</div><div>✓ Local audit state saved</div><div>○ HMRC not connected</div><div>○ Bank not connected</div></div><button class='btn' onclick='home()'>Dashboard</button></div>`}
function resetPayroll(){approved=false;localStorage.removeItem('spApproved');pay()}
function payslip(id){let e=employees.find(x=>x.id===id),gross=e.current||e.normal,estimatedTax=gross*.12,estimatedNi=gross*.06,net=gross-estimatedTax-estimatedNi;app.innerHTML=demo()+`<button class='btn light' onclick='profile(${id})'>← ${e.name}</button><div class='payslip'><div class='top'><div><h2>SimplePay</h2><div class='muted'>Demo payslip · October 2026</div></div><b>${company}</b></div><hr><h3>${e.name}</h3><table class='paytable'><tr><td>Gross pay</td><td>${money(gross)}</td></tr><tr><td>Illustrative tax</td><td>−${money(estimatedTax)}</td></tr><tr><td>Illustrative NI</td><td>−${money(estimatedNi)}</td></tr><tr><th>Illustrative net pay</th><th>${money(net)}</th></tr></table><p class='muted'><b>Prototype only:</b> these deductions are illustrative, not HMRC payroll calculations.</p></div>`}
function time(){app.innerHTML=demo()+`<h1>Time</h1><div class='grid'><div class='card'><h3>October hours</h3><p class='ok'>✓ Demo hours imported</p><div class='warning'>Sarah Jones · 32 overtime hours</div></div><div class='card'><h3>Future connections</h3><p>CSV upload<br>Rota systems<br>Clock-in systems<br>API</p></div></div>`}
function settings(){app.innerHTML=demo()+`<h1>Settings</h1><div class='grid'><div class='card'><h3>Company</h3><label>Company name</label><input id='company' value="${company}"><button class='btn' onclick="company=document.querySelector('#company').value;localStorage.setItem('spCompany',company);home()">Save</button></div><div class='card'><h3>Connections</h3><p>HMRC <b>Not connected</b></p><p>Bank <b>Not connected</b></p><p>Pension <b>Not connected</b></p></div></div><div class='card' style='margin-top:18px'><h3>Rules engine</h3><p><b>Target tax year: 2026/27</b></p><p class='muted'>The live calculation engine is not enabled in this UI prototype yet.</p><button class='btn light' onclick='resetAll()'>Reset all demo data</button></div>`}
function resetAll(){localStorage.clear();employees=[...seed];approved=false;company="Dave's Plumbing Ltd";home()}render();